name: "Setup Node.js"
description: "Setup Node.js"
author: "Ben Grynhaus <ben@brandtotal.com>"
runs:
  using: "node12"
  main: "dist/main.js"
  post: "dist/cleanup.js"
branding:
  icon: "box"
  color: "green"
