name: "Yarn install"
description: "Yarn install with authentication and caching"
author: "Ben Grynhaus <ben@brandtotal.com>"
runs:
  using: "node12"
  main: "dist/main.js"
  post: "dist/cleanup.js"
inputs:
  registryUrl:
    required: false
    description: A registry url to install from
